booking:
  property: Product Profile Dev

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: productdb
      port: 27017
      host: 127.0.0.1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

app:
  test-property: Testing properties