booking:
  property: Product Profile Dev

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

app:
  test-property: Testing properties updated by Bus Rabbit